### ISSUE TITLE
Обработка кавычек

### ISSUE THREAD

**Issue by alex-revo** [fiction13/pkg_radicalmicro#15]
Нужно добавить обработку кавычек и спец.символов, иначе при вводе например, название: ООО "ИмпериалТехноСтрой"
у нас заголовок в Og title = ООО
![image](https://user-images.githubusercontent.com/7030604/185675635-77c68372-75d5-4971-bbe4-389a21754c34.png)

**Comment by fiction13** [comment]
> Нужно добавить обработку кавычек и спец.символов, иначе при вводе например, название: ООО "ИмпериалТехноСтрой" у нас заголовок в Og title = ООО

Кавычки - вообще зло.

Вариантов-то немного.

- Html сущности (надо проверить, как их обработают соц. сети)
- Удаление совсем
- Замена на одинарные кавычки

Какой лучше?

**Comment by alex-revo** [comment]
Думаю нужно пробовать преобразовать в HTML сущности, проверить потом не долго.

**Comment by dmitriitux** [comment]
> > Нужно добавить обработку кавычек и спец.символов, иначе при вводе например, название: ООО "ИмпериалТехноСтрой" у нас заголовок в Og title = ООО
> 
> Кавычки - вообще зло.
> 
> Вариантов-то немного.
> 
> * Html сущности (надо проверить, как их обработают соц. сети)
> * Удаление совсем
> * Замена на одинарные кавычки
> 
> Какой лучше?

в сущности обычно делают такое
