### ISSUE TITLE
Добавить параметры высоты и ширины

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#17]
```
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
```

параметры настраиваемые в плагине - вдруг стандарты поменяются.
возможно, в элементе эти параметры переопределение добавить опциональное. 
это для других типов разметок типа фильмы.  предполагаю, там вертикальные картинки.

**Comment by fiction13** [comment]
Добавлено
