### ISSUE TITLE
Указывать тип разметки

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#18]
типов много:
<img width="511" alt="Снимок экрана 2022-09-17 в 08 59 25" src="https://user-images.githubusercontent.com/3432048/190842890-ae7de2a3-351e-4a00-be06-ebbca41c1322.png">

возможно, влияет на отображение в FB.
предлагаю юзеру дать возможность выбора типа в элементе.
как минимум, пригодиться могут:
article
blog
product

**Comment by fiction13** [comment]
У пользователя и так есть выбор указания разметки.

Я что-то не понимаю :-)

**Comment by Sulpher** [comment]
а, ок. извини. это я по горячим следам изучения иного плагина написал, не посмотрев в настройки radicalmicro.
