### ISSUE TITLE
RadicalMicro Meta Element

### ISSUE THREAD

**Issue by alex-revo** [fiction13/pkg_radicalmicro#2]
Нужно доработать перевод на английский
![image](https://user-images.githubusercontent.com/7030604/172504333-8f8123f9-9e10-43e0-b9b7-3f12dec07be6.png)

Это поле не нужно делать динамическим
![image](https://user-images.githubusercontent.com/7030604/172504401-85a660b5-6b91-4ed5-aecd-467ad6dc8ee8.png)
Если там дискретный набор значений, то лучше задать его списком

**Comment by fiction13** [comment]
Глобально я не вижу ничего плохого в добавлении динамики полю.

Но на самом деле я бы сделал это поле disabled, потому что оно может смущать неопытного пользователя, а с использованием других типов я ни разу не сталкивался.

Вот список типов для разметки - https://ruogp.me/#types

Вообще все поля настроек элементов формируются и добавляются в конфиг элемента динамически, поэтому для этого конкретного поля конечно можно сделать список, но он будет очень большой. 

Переводы будут в следующей версии, пропустил.

**Comment by alex-revo** [comment]
Disabled - хороший вариант.

В целом этот элемент у меня не работает или я что-то не понимаю.
На странице после добавления элемента появился только такой код
![image](https://user-images.githubusercontent.com/7030604/173024587-f831d79e-0a3d-4426-8522-06b021250542.png)

**Comment by fiction13** [comment]
Я тебе напишу, проверим.

**Comment by alex-revo** [comment]
Дима мне подсказал, оказывается этот плагин зависим от настроек в основном плагине, где они все по умолчанию выключены, поэтому никакой Og/Twitter разметки не появляется.
Как минимум нужно добавить в описание плагина что зависимые настройки нужно искать в другом плагине.
Как мамсимум по умолчанию включать все опции внутри основного плагина.

**Comment by fiction13** [comment]
Да, я думаю, что логично включить настройки по умолчанию. И в элементах написать, что элементы связаны с плагином.

Пока оставлю открытым.

Сейчас в элементе делаются правки объединения типов (OG и Twitter), чтобы не добавлять для каждого типа свой элемент.

**Comment by alex-revo** [comment]
Согласен, в одном элементе будет удобней.

**Comment by fiction13** [comment]
Настройки по умолчанию включил.

Добавление текста в элементы, что они зависят от настроек основного плагина, добавил в отдельный Issue.
