### ISSUE TITLE
добавить параметр Full image

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#20]
Radical Micro - Defaults 
на выбор картинка из контента или into image. 
предлагаю добавить на выбор и full image.

у меня в интро изображениях картинки квадратной пропорции. (логотипы), а для OG было бы удобнее задействовать full image. можно перелопатить все материалы и поменять местами, но для гибкости лучше ввести  доп параметр.

**Comment by Sulpher** [comment]
<img width="739" alt="Снимок экрана 2022-09-23 в 22 47 44" src="https://user-images.githubusercontent.com/3432048/192046390-6dbd59b2-c921-455e-a026-acf30f017569.png">

**Comment by fiction13** [comment]
Этот плагин понятия не имеет про Intro image или Full Image, если речь идет о com_content. Для этого используй соответсnвующий плагин для com_content. Там можно выбрать одно из этих изображений.

Данный плагин Defaults призван лишь добавить значения на тех страницах, где нет плагинов провайдеров исходя из данных, которые есть на странице. Он может подставлять или статичное изображение, указанное в настройках, или парсить страницу и брать первое попавшееся.

**Comment by fiction13** [comment]
Единственное, что сюда можно добавить - это сколько изображений пропускать. 

Брать не первое (а то оно может быть маленьким логотипом), а второе, третье и так далее опционально.
