### ISSUE TITLE
Лишний префикс в пути к картинке: #joomlaImage://local-images

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#22]
из-за особенностей Joomla 4, к картинкам принудительно добавляется префикс с размерами:
`<meta property="og:image" content="https://domain.ru/images/app-for-jomsocial.png#joomlaImage://local-images/video-thumbs/app-for-jomsocial.png?width=1280&height=720" />`

FB debugger  на такое может отреагировать негативно.

предлагаю регуляркой вычищать из кода лишнее, чтобы путь был чистым.

**Comment by fiction13** [comment]
Fixed with commit https://github.com/fiction13/pkg_radicalmicro/commit/fc3c97b3e020c993aaf331f15d8da591abc1fd58
