### ISSUE TITLE
Дополнительные параметры

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#25]
посмотрел еще решения, вот такие параметры еще добавляют:
```
	<meta property="og:headline" content="{ТУТ ДУБЛЬ ОПИСАНИЯ САЙТА - meta-description}" />
        <meta property="og:site_name" content="Russian24" />
	<meta property="og:locale" content="ru_RU" />
```
и еще размеры высоты и ширины (об этом есть issue: https://github.com/fiction13/pkg_radicalmicro/issues/17)

без них работает, но можно добавить,  будет полный порядок.

**Comment by fiction13** [comment]
Добавлены site_name и locale. Site_name можно прописан в плагине Значения по умолчанию.
