### ISSUE TITLE
0 Class 'RadicalMicro\Helpers\PathHelper' not found 

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#26]
если отключен плагин системный, то при попытке зайти в контент плагин, получаю ошибку:
<img width="1015" alt="Снимок экрана 2022-10-06 в 17 04 22" src="https://user-images.githubusercontent.com/3432048/194334297-fb13d17b-ffc3-4ac4-9f25-9bf1eb272fb9.png">

нужно сделать проверку и вывести предупреждение вместо ошибки.

**Comment by fiction13** [comment]
Fixed with commit https://github.com/fiction13/pkg_radicalmicro/commit/fc3c97b3e020c993aaf331f15d8da591abc1fd58
