### ISSUE TITLE
[Баг] В материале наследуется картинка из блога категории 

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#27]
контент плагин: выбрано image intro.  

<img width="916" alt="Снимок экрана 2022-10-06 в 17 31 16" src="https://user-images.githubusercontent.com/3432048/194341135-cd43c056-9a4a-480f-bc6f-cb78897f6b50.png">

вот картинка материала:
<img width="1020" alt="Снимок экрана 2022-10-06 в 17 31 04" src="https://user-images.githubusercontent.com/3432048/194341300-518b3311-3dfd-4f53-9111-c3327072beae.png">

а в коде тянется картинки с пункта меню блог категории:

`<meta property="og:image" content="https://site.ru/images/og-default1.png#joomlaImage://local-images/og-default1.png?width=1200&height=630" />`

вместо картинки материала берется картинка из пункта меню на блог категории.

**Comment by fiction13** [comment]
Fixed with commit https://github.com/fiction13/pkg_radicalmicro/commit/fc3c97b3e020c993aaf331f15d8da591abc1fd58
