### ISSUE TITLE
Переименовать параметры

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#28]
<img width="880" alt="Снимок экрана 2022-10-06 в 17 27 09" src="https://user-images.githubusercontent.com/3432048/194341715-eba11c8b-67c2-43a9-b0a6-b6d92170fafb.png">

два параметра последних: это должны быть input поля.  указать один раз и достаточно.

и переименовать согласно стандарту твиттер.

```
<meta name="twitter:site" content=" " />
<meta name="twitter:creator" content=" " />
```

Twitter site, Twitter creator

**Comment by fiction13** [comment]
Fixed with commit https://github.com/fiction13/pkg_radicalmicro/commit/fc3c97b3e020c993aaf331f15d8da591abc1fd58
