### ISSUE TITLE
Вкладка с параметрами при редактировании материала

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#29]
две проблемы:
1. нужно вывести select для поля картинки вместо input.

2. изменения не сохраняются.
<img width="1038" alt="Снимок экрана 2022-10-06 в 17 22 24" src="https://user-images.githubusercontent.com/3432048/194342563-bbb267bd-4da3-4b50-985e-274ba2e0ccea.png">
 
вот так. нажимаю на enable, пишу путь, сохраняю и снова отключено.
то есть, не могу зафиксировать изменения.
с соседней вкладкой микродаты тот же эффект. правда, я микродату отключил в настройках

**Comment by fiction13** [comment]
Fixed with commit fc3c97b3e020c993aaf331f15d8da591abc1fd58
