### ISSUE TITLE
Убрать три точки в конце мета-описания

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#31]
<img width="1028" alt="Снимок экрана 2023-02-19 в 18 03 47" src="https://user-images.githubusercontent.com/3432048/219956447-beaee69e-0ab9-47a9-bf89-2dd779dd9383.png">

описание:
`Практический урок, в рамках которого рассмотрим, как автоматически выводить текущий год в футере сайта, созданного на базе Joomla и YOOtheme Pro.`

в исходном коде я вижу такое:

`<meta property="og:description" content="Практический урок, в рамках которого рассмотрим, как автоматически выводить текущий год в футере сайта, созданного на базе Joomla и YOOtheme Pro...." />`

в конце почему-то три символа: ... (не символ троеточия, а именно три символа .)
если описание меньше 160 символов, не нужно выводить три точки.
а если больше, то можно заменить на этот  символ: …

**Comment by Sulpher** [comment]
версия 0.2.4

**Comment by Sulpher** [comment]
такой эффект возникает в случае, если описание на 146 символов. попробуй пример выше. 
если меньше - все ок.

**Comment by fiction13** [comment]
Увеличена ширина текста до 300 символов
