### ISSUE TITLE
Title пункта меню не подставляется в OG title

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#32]
несоответствие.

вот такой тайтл:
`<title>создание Интернет-магазинов под ключ</title>`

а в og вот так:
```
<!-- RadicalMicro: start -->
<meta property="og:title" content="Главная страница" />
```

а в og должно быть как в title вместо названия пункта меню.
версия 2.0.4

чтобы решить проблему,: нужно в пункте меню включить во вкладке radicalmicro параметр и продублировать значение, что неудобно

**Comment by fiction13** [comment]
Скачай версию прямо из репы, поставь на тестовом и проверь, может я уже правил эту проблему, я не помню.

**Comment by fiction13** [comment]
Пока закрою, если проблема есть, то открой заново.
