### ISSUE TITLE
Названия парамеров микро-разметки  - правки

### ISSUE THREAD

**Issue by Sulpher** [fiction13/pkg_radicalmicro#38]
микро-разметка - организация.

**Страна**. нужно пояснить, что указывать нужно по  стандарту ISO 3166-2. т.е. RU

**Почтовый ящик** - второй параметр: 
я вообще не понял, что это. а это, полагаю, абонентский ящик: 
        "postOfficeBoxNumber": "111",

т.е. нужно переименовать, чтобы понятнее было.

**Comment by kernusr** [comment]
> микро-разметка - организация.
> 
> **Страна**. нужно пояснить, что указывать нужно по стандарту ISO 3166-2. т.е. RU
> 

В русском варианте?
```ini
PLG_SYSTEM_RADICALMICRO_PARAM_SCHEMA_TYPE_ORGANIZATION_COUNTRY = "Код страны"
PLG_SYSTEM_RADICALMICRO_PARAM_SCHEMA_TYPE_ORGANIZATION_COUNTRY_DESC  = "Код страны организации, в соответствии с ISO 3166-2, для разметки типа Organization"
```
в английском
```ini
PLG_SYSTEM_RADICALMICRO_PARAM_SCHEMA_TYPE_ORGANIZATION_COUNTRY = "Country code"
PLG_SYSTEM_RADICALMICRO_PARAM_SCHEMA_TYPE_ORGANIZATION_COUNTRY_DESC = "Organization country code, according to ISO 3166-2, for Organization layout"
```

Норм?
