### ISSUE TITLE
Пояснения для полей

### ISSUE THREAD

**Issue by dmitriitux** [fiction13/pkg_radicalmicro#6]
![image_2022-07-04_15-01-00](https://user-images.githubusercontent.com/6643167/177150695-a1da5245-ed3d-4040-8d3a-07976519efcf.png)

- Непонятно что такое почтовый ящик, что имеется ввиду? e-mail? или что?
- Основная разметка что это?

**Comment by fiction13** [comment]
Почтовый ящик - это номер почтового ящика для адресов абонентских ящиков. Пояснение добавлю.

**Comment by fiction13** [comment]
Под основной разметкой я подразумеваю разметки Article, NewsArticle, Recipe и так далее, которым размечен основной контент страницы. 

За ее включение отвечает переключатель. По умолчанию наверно надо сделать включенным.
